base/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('museum.urls')),
    path('admin/', admin.site.urls),
]

museum/urls.py
from django.urls import path
from . import views

app_name = 'museum'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_user, name='logout'),
    path('login/', views.login_user, name='login'),
    path('password_forgotten/', views.password_forgotten, name='password_forgotten'),

]

museum/models.py
from django.db import models

# Create your models here.

museum/views.py
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User


def index(request):
    return render(request,  'index.html')
    # return HttpResponse('Hello world!@ test')


def signup(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Цей логін вже зайнятий!')
                return redirect('signup')
            else:
                user = User.objects.create_user(email=email, password=password, username=username)
                user.save()
                return redirect('/')
    else:
        return render(request, 'signup.html')


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('museum:index')
        else:
            messages.error(request, "Дані введено некоректно")

    return render(request, 'login.html')


def logout_user(request):
    logout(request)
    return redirect('museum:index')



def password_forgotten(request):
    return render(request,  'passwordforgotten.html')

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MUSEUM</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
        html {
            scroll-behavior: smooth; /* повільно переходити з елемента на елемент */
        }
    </style>
</head>
<body>
    <header id="header" class="header">
        <div class="container">
            <div class="nav">
                <h1 class="header_title">
                    <a href="">
                        MUSEUM
                    </a>
                </h1>
                <nav class="menu">
                    <a href="shop.html" class="btn">
                        Магазин
                    </a>
                    <ul>
                        <li>
                            <a href="visit.html">
                                Відвідати
                            </a>
                        <li>
                            <a href="exhibitions.html">
                                Виставки та події
                            </a>
                        </li>
                        <li>
                            <a href="collections.html">
                                Колекція
                            </a>
                        </li>
                        <li>
                            <a href="membership.html">
                                Членство
                            </a>
                        </li>
                        <li>
                            <a href="supportus.html">
                                Підтримати нас
                            </a>
                        </li>
                        {% if user.is_authenticated %}
                            <li>
                                <p style="color: white">{{ request.user }}</p>
                            </li>
                        {% else %}
                                <a href="{% url 'museum:login' %}">
                                    Вхід
                                </a>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <section id="main" class="main">
        <div class="background_image"></div>
        <div id="info_box" class="info_box">
            <h1 class="main_title">Ласкаво просимо до музею</h1>
            <p>Пізнай культуру всього світу, від світанку людської історії до сьогодення.</p>
            <h2>
                <a href="visit.html" class="shop_btn">
                    Спланувати візит
                </a>
            </h2>
        </div>
    </section>
    <!-- <section id="hero" class="hero">
        <div class="container">
            <div class="display">
                <div class="text">
                    <h1>Досліди два мільйони років людської історії та культури</h1>
                    <div class="info">
                        <p>Безкоштовний вхід - зареєструватися онлайн</p>
                        <p>Відкритий сьогодні: 10:00 - 16:00</p>
                        <p>Останній вхід: 15:00</p>
                    </div>
                </div>
            </div>
    </section>
    <section id="main" class="main">
        <div class="container">
            <hr>
        </div>
    </section> -->
    <footer id="footer" class="footer">
        <div class="container">
            <div class="container">
                <span>Copyright © 2023 | BSFY</span>
            </div>
        </div>
    </footer>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вхід</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login.css' %}">
</head>

<body>
    <section>
        <form action="" method="POST">
            {% csrf_token %}
            <h1>Вхід</h1>
            <div class="inputbox">
                <ion-icon name="mail-outline"></ion-icon>
                <input type="text" name="username" required>
                <label>Логін</label>
                <!-- <span class="error-message" id="email-error"></span> -->
            </div>

            <div class="inputbox">
                <ion-icon name="lock-closed-outline"></ion-icon>
                <input id="passwordInput" type="password" name="password" required>
                <label>Пароль</label>
                <i class="far fa-eye-slash eye-icon" id="togglePassword"></i>
            </div>

            <div class="forget">
                <a href="{% url 'museum:password_forgotten' %}">Забули пароль</a>
            </div>
            <button>Увійти</button>
            <div class="register">
                <p>Немає? <a href="{% url 'museum:signup' %}">Зареєструватися</a></p>
            </div>
        </form>
    </section>

    <script>
        const passwordInput = document.getElementById('passwordInput');
        const togglePassword = document.getElementById('togglePassword');

        togglePassword.addEventListener('click', function () {
            const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
            passwordInput.setAttribute('type', type);
            this.classList.toggle('fa-eye');
            this.classList.toggle('fa-eye-slash');
        });
    </script>
</body>

</html>

templates/passwordforgotten.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Відновлення пароля</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'login.css' %}">
</head>

<body>
    <section>
        <form>
            <h1>Не вдається ввійти?</h1>
            <div class="register">
                <p>Укажіть електронну адресу і ми надішлемо вам посилання для відновлення доступу до облікового запису.</p>
            </div>
            <div class="inputbox">
                <ion-icon name="mail-outline"></ion-icon>
                <input type="email" required>
                <label>Введіть електронну пошту</label>
                <span class="error-message" id="email-error"></span>
            </div>

            <button>Надіслати посилання</button>
        </form>
    </section>

    <script>
        const passwordInput = document.getElementById('passwordInput');
        const showPasswordCheckbox = document.getElementById('showPassword');

        showPasswordCheckbox.addEventListener('change', function () {
            if (this.checked) {
                passwordInput.type = 'text';
            } else {
                passwordInput.type = 'password';
            }
        });
    </script>
</body>

</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Реєстрація</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login.css' %}">
</head>

<body>
<section>
    <form action="" method="POST">
        {% csrf_token %}

        <h1>Реєстрація</h1>

        <div>
            {% for message in messages %}
            <h5>{{message}}</h5>
            {% endfor %}
        </div>

        <div class="inputbox">
            <ion-icon name="mail-outline"></ion-icon>
            <input type="email" name="email" required>
            <label>Електронна пошта</label>
        </div>
        <div class="inputbox">
            <ion-icon name="mail-outline"></ion-icon>
            <input type="text" name="username" required>
            <label>Логін</label>
        </div>

        <div class="inputbox">
            <ion-icon name="lock-closed-outline"></ion-icon>
            <input id="passwordInput" type="password" name="password" required>
            <label>Пароль</label>
            <i class="far fa-eye-slash eye-icon" id="togglePassword1"></i>
        </div>

        <div class="inputbox">
            <ion-icon name="lock-closed-outline"></ion-icon>
            <input id="confirmPasswordInput" type="password" name="password2" required>
            <label>Повторіть пароль</label>
            <i class="far fa-eye-slash eye-icon" id="togglePassword2"></i>
        </div>
        <button type="submit">Зареєструватися</button>
    </form>
</section>

<script>
    const passwordInput = document.getElementById('passwordInput');
    const confirmPasswordInput = document.getElementById('confirmPasswordInput');
    const togglePassword1 = document.getElementById('togglePassword1');
    const togglePassword2 = document.getElementById('togglePassword2');

    togglePassword1.addEventListener('click', function () {
        const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordInput.setAttribute('type', type);
        this.classList.toggle('fa-eye');
        this.classList.toggle('fa-eye-slash');
    });

    togglePassword2.addEventListener('click', function () {
        const type = confirmPasswordInput.getAttribute('type') === 'password' ? 'text' : 'password';
        confirmPasswordInput.setAttribute('type', type);
        this.classList.toggle('fa-eye');
        this.classList.toggle('fa-eye-slash');
    });

</script>

</body>

</html>